---
type: "posts"
baseURL: https://atmoschem.github.io/
title: atmoschem
theme: hugo-geekdoc
pygmentsUseClasses: true
pygmentsCodeFences: true
timeout: 180000
pluralizeListTitles: false

type: "posts"

# Geekdoc configuration
disablePathToLower: true
enableGitInfo: true

# Needed for mermaid shortcodes
markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 1
    endLevel: 9

params:
  mainSections: ["post"]
  # geekdocMenuBundle: true
  geekdocToC: 3

  geekdocRepo: https://github.com/atmoschem/atmoschem.github.io
  # geekdocEditPath: edit/main/exampleSite/content

  geekdocSearch: true
  geekdocSearchShowParent: true

  #geekdocLegalNotice: https://thegeeklab.de/legal-notice/#contact-information
  #geekdocPrivacyPolicy: https://thegeeklab.de/legal-notice/#privacy-policy

  geekdocImageLazyLoading: true
  geekdocDarkModeDim: true
